### ISSUE TITLE
File name too long on save file

### ISSUE THREAD

**Issue by fpolli** [lukaslaobeyer/3dtiles-dl#1]
Hi, I tried to run this script and after having to install a couple of modules, it appeared to run, but dumped with an error:

```
python3 -m scripts.download_tiles -k my-api-access-token-bobloblaw -c 41.89316424773806 12.476527030603998 -r 500 -o tiles
Querying elevation...
Traversing tile hierarchy...
673it [00:03, 172.12it/s]
Downloading tiles...
  0%|                                                   | 0/673 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/fred/scripts/3dtiles-dl/scripts/download_tiles.py", line 65, in <module>
    with open(outdir / Path(f"{t.basename}.glb"), "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: 'tiles/UlRPVEYubm9kZWRhdGEucGxhbmV0b2lkPWVhcnRoLG5vZGVfZGF0YV9lcG9jaD05NTkscGF0aD0zMDQxNzE0MTczNDI3MjY1NzE1NixjYWNoZV92ZXJzaW9uPTYsaW1hZ2VyeV9lcG9jaD05ODEsYWxpZ25tZW50X3ZlcnNpb249Uk9DS1RSRUVfOTkyX0dPT0dMRV9EQVRVTV8yMDI0MDgwN1QwNzUzWl9nZW5lcmF0ZWRfYXRfMjAyNDEyMTBUMTMwN1o.glb'
```
I am running Linux Mint 22 (ubuntu 24.04)

**Comment by lukaslaobeyer** [comment]
I haven't run into this before, but you could edit the script to try using a shorter filename to save the tiles to, instead of the `basename` which appears to be very long here. For example...
```diff
- with open(outdir / Path(f"{t.basename}.glb"), "wb") as f:
+ with open(outdir / Path(f"{i:06d}.glb"), "wb") as f:
```

**Comment by fpolli** [comment]
Dude you fooking rawk! That worked. I now have 673 glb files sitting in a directory I need to figure out what to do with. :)
